name: Run Hive Integration Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: "${{ github.workflow }} @ ${{ github.ref }}"
  cancel-in-progress: true

jobs:
  trigger-hive-tests:
    name: Trigger Hive Integration Tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: Bearer ${{secrets.HIVETEST_TOKEN}}" \
          https://api.github.com/repos/taikoxyz/hive/dispatches \
          -d '{"event_type":"start","client_payload":{"repo":"${{ github.repository }}", "ref": "${{ github.head_ref || github.ref }}" }}'
